/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-08 07:06:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._01_005fStudents;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class easy_005fstudents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("   <meta charset=\"UTF-8\">\n");
      out.write("   <title>Insert title here</title>\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/easyui.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/icon.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/demo.css\">\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-3.5.1.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery.easyui.min.js\"></script>\n");
      out.write("    <script>\n");
      out.write("       $(document).ready (\n");
      out.write("          function() {\n");
      out.write("             $(\"#btnSearch\").click (\n");
      out.write("                function() {\n");
      out.write("                   $(\"#dg\").datagrid({\n");
      out.write("                      url : \"./datas/getSelStudent.jsp?stu_id=\" +$(\"#stu_id\").val()\n");
      out.write("                      , singleSelect:true\n");
      out.write("                      , rowStyler:function(index, row) {\n");
      out.write("                                if(row.stu_name.indexOf('홍') != -1) {\n");
      out.write("                                   return 'background-color:pink;'\n");
      out.write("                                }\n");
      out.write("                             }\n");
      out.write("                      , checkOnSelect:false\n");
      out.write("                      , selectOnCheck:false\n");
      out.write("                   });\n");
      out.write("                }      \n");
      out.write("             );\n");
      out.write("          }      \n");
      out.write("       );\n");
      out.write("       \n");
      out.write("       var editIndex = undefined;\n");
      out.write("       \n");
      out.write("       function endEditing(){\n");
      out.write("            if (editIndex == undefined){return true}\n");
      out.write("            if ($('#dg').datagrid('validateRow', editIndex)){\n");
      out.write("                $('#dg').datagrid('endEdit', editIndex);\n");
      out.write("                editIndex = undefined;\n");
      out.write("                return true;\n");
      out.write("            } else {\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("       function endEdit(index, row){\n");
      out.write("            /*\n");
      out.write("          var ed = $(this).datagrid('getEditor', {\n");
      out.write("                index: index,\n");
      out.write("                field: 'productid'\n");
      out.write("            });\n");
      out.write("            row.productname = $(ed.target).combobox('getText');\n");
      out.write("            */\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       function clickCell(index, field){\n");
      out.write("            if(editIndex != index) {\n");
      out.write("                if(endEditing()) {\n");
      out.write("                    $('#dg').datagrid('selectRow', index)\n");
      out.write("                            .datagrid('beginEdit', index);\n");
      out.write("                    var ed = $('#dg').datagrid('getEditor', {index:index,field:field});\n");
      out.write("                    if (ed){\n");
      out.write("                        ($(ed.target).data('textbox') ? $(ed.target).textbox('textbox') : $(ed.target)).focus();\n");
      out.write("                    }\n");
      out.write("                    editIndex = index;\n");
      out.write("                } else {\n");
      out.write("                    setTimeout(function(){\n");
      out.write("                        $('#dg').datagrid('selectRow', editIndex);\n");
      out.write("                    },0);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("       function append(){\n");
      out.write("            if (endEditing()){\n");
      out.write("                $('#dg').datagrid('appendRow',{status:'P'});\n");
      out.write("                editIndex = $('#dg').datagrid('getRows').length-1;\n");
      out.write("                $('#dg').datagrid('selectRow', editIndex)\n");
      out.write("                        .datagrid('beginEdit', editIndex);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("        function removeit(){\n");
      out.write("            if (editIndex == undefined){return}\n");
      out.write("            $('#dg').datagrid('cancelEdit', editIndex)\n");
      out.write("                    .datagrid('deleteRow', editIndex);\n");
      out.write("            editIndex = undefined;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function acceptit(){\n");
      out.write("            if (endEditing()){\n");
      out.write("                $('#dg').datagrid('acceptChanges');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function reject(){\n");
      out.write("            $('#dg').datagrid('rejectChanges');\n");
      out.write("            editIndex = undefined;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function getChanges(){\n");
      out.write("            var rows = $('#dg').datagrid('getChanges');\n");
      out.write("            alert(rows.length+' rows are changed!');\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   <h2>Basic DataGrid</h2>\n");
      out.write("    <p> DB 프로시져가 중요하다 </p>\n");
      out.write("    <div style=\"margin:20px 0;\"></div>\n");
      out.write("    <div>\n");
      out.write("       <input class=\"easyui-tetxtbox\" name=\"stu_id\" id=\"stu_id\"/>\n");
      out.write("       <input type=\"button\" id=\"btnSearch\" value=\"검색\"/>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"margin:20px 0;\"></div>\n");
      out.write("    <table class=\"easyui-datagrid\" id=\"dg\" title=\"Basic DataGrid\" style=\"width:900px;height:500px\"\n");
      out.write("           data-options=\"singleSelect:false,\n");
      out.write("                         collapsible:true,\n");
      out.write("                         url:'./Datas/getStudents.jsp',\n");
      out.write("                         method:'get',\n");
      out.write("                         rownumbers:true,\n");
      out.write("                         rowStyler:function(index, row) {\n");
      out.write("                            if(row.stu_name.indexOf('홍') == -1) {\n");
      out.write("                               return 'background-color:lavender;'\n");
      out.write("                            }\n");
      out.write("                         },\n");
      out.write("                         checkOnSelect:true,\n");
      out.write("                         selectOnCheck:true,\n");
      out.write("                         toolbar:'#tb',\n");
      out.write("                         onClickCell:clickCell,\n");
      out.write("                         onEndEdit:endEdit\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("               <th data-options=\"field:'ck',checkbox:true\"></th>\n");
      out.write("                <!-- <th data-options=\"field:'stu_id',width:100,align:'center'\">아이디</th> -->\n");
      out.write("                <th data-options=\"field:'stu_id',width:100,align:'center'\n");
      out.write("                ,formatter : function(value, row){\n");
      out.write("               \t\treturn row.stu_name;\n");
      out.write("                }\n");
      out.write("                ,editor:{\n");
      out.write("               \t\ttype: 'combobox',\n");
      out.write("               \t\toptions:{\n");
      out.write("               \t\t\tvalueField : 'stu_id',\n");
      out.write("               \t\t\ttextField : 'stu_name',\n");
      out.write("               \t\t\tmethod : 'get',\n");
      out.write("               \t\t\turl : './Datas/getStudents.jsp',\n");
      out.write("               \t\t\trequired : true\n");
      out.write("                \t}\n");
      out.write("                }\n");
      out.write("                \">이름</th>\n");
      out.write("                <th data-options=\"field:'stu_tel',width:150,align:'center',editor:'textbox'\">연락처</th>\n");
      out.write("                <th data-options=\"field:'stu_addr',width:200,align:'center'\n");
      out.write("                ,formatter : function(value, row){\n");
      out.write("               \t\treturn row.stu_addr;\n");
      out.write("               \t}\n");
      out.write("               \t,editor:{\n");
      out.write("               \t\ttype: 'combobox',\n");
      out.write("               \t\toptions:{\n");
      out.write("               \t\t\tvalueField : 'stu_addr',\n");
      out.write("               \t\t\ttextField : 'stu_addr',\n");
      out.write("               \t\t\tmethod : 'get',\n");
      out.write("               \t\t\turl : './Datas/getStudents.jsp',\n");
      out.write("               \t\t\trequired : true\n");
      out.write("               \t\t}\n");
      out.write("               \t}\n");
      out.write("               \t\">주소</th>\n");
      out.write("                <th data-options=\"field:'stu_dept',width:200,align:'center'\n");
      out.write("                ,formatter : function(value, row){\n");
      out.write("               \t\treturn row.stu_dept;\n");
      out.write("               \t}\n");
      out.write("               \t,editor:{\n");
      out.write("               \t\ttype: 'combobox',\n");
      out.write("               \t\toptions:{\n");
      out.write("               \t\t\tvalueField : 'stu_dept',\n");
      out.write("               \t\t\ttextField : 'stu_dept',\n");
      out.write("               \t\t\tmethod : 'get',\n");
      out.write("               \t\t\turl : './Datas/getStudents.jsp',\n");
      out.write("               \t\t\trequired : true\n");
      out.write("               \t\t}\n");
      out.write("               \t}\n");
      out.write("               \t\">학과</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("    </table>\n");
      out.write("    <!--\n");
      out.write("    <div style=\"margin:20px 0;\"></div>\n");
      out.write("    <table class=\"easyui-datagrid\" title=\"Basic DataGrid\" style=\"width:850px;height:500px\"\n");
      out.write("           data-options=\"singleSelect:false,\n");
      out.write("                         collapsible:true,\n");
      out.write("                         url:'./datas/getStudents.jsp',\n");
      out.write("                         method:'get',\n");
      out.write("                         rownumbers:true\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("               <th data-options=\"field:'ck',checkbox:true\"></th>\n");
      out.write("                <th data-options=\"field:'stu_id',width:100,align:'center'\">아이디</th>\n");
      out.write("                <th data-options=\"field:'stu_name',width:100,align:'center',editor:'textbox'\">이름</th>\n");
      out.write("                <th data-options=\"field:'stu_tel',width:150,align:'center',editor:'textbox'\">연락처</th>\n");
      out.write("                <th data-options=\"field:'stu_addr',width:250,align:'center'\">주소</th>\n");
      out.write("                <th data-options=\"field:'stu_dept',width:200,align:'center'\">학과</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("    </table>\n");
      out.write("    -->\n");
      out.write("    <div id=\"tb\" style=\"height:auto\">\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\" onclick=\"append()\">Append</a>\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-remove',plain:true\" onclick=\"removeit()\">Remove</a>\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save',plain:true\" onclick=\"acceptit()\">Accept</a>\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-undo',plain:true\" onclick=\"reject()\">Reject</a>\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search',plain:true\" onclick=\"getChanges()\">GetChanges</a>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
