/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-06 08:08:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._02_005fScores;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/scores.css\" />\n");
      out.write("<style>\n");
      out.write("\t#dept {\n");
      out.write("\t\tdisplay: none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#student {\n");
      out.write("\t\tdisplay: none;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\n");
      out.write("<script src=\"../js/scores.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$( function(){\n");
      out.write("\t\t// 시험학기(년도, 학기)\n");
      out.write("\t\tgetYear('year');\n");
      out.write("\t\t\n");
      out.write("\t\tgetCollege('college');\n");
      out.write("\t\t\n");
      out.write("\t\t// CHANGE 이벤트 등록 \n");
      out.write("\t\t$('#college').change( function(){\n");
      out.write("\t\t\tvar selectedValue = $('#college').val();\n");
      out.write("\t\t\tgetDept(selectedValue, 'dept'); // selectedValue로 학과 정보를 가져와야함\n");
      out.write("\t\t\t//$('#dept').show();\n");
      out.write("\t\t\t$('#dept').css('display','inline');\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('#dept').change( function(){\n");
      out.write("\t\t\tvar selectedValue = $('#dept').val();\n");
      out.write("\t\t\tgetStudents(selectedValue, 'student');\n");
      out.write("\t\t\t$('#student').show();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('#student').change( function(){\n");
      out.write("\t\t\tvar stu_id   = $('#student').val();\n");
      out.write("\t\t\tvar syear    = $('#year').val();\n");
      out.write("\t\t\tvar semester = $('#semester').val(); // 선택된 값들을 변수에 담아서\n");
      out.write("\t\t\tgetSubjects(stu_id, syear, semester, 'subject'); // 인자로 넘겨 과목 조회\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$('#btnSave').click( function(){\n");
      out.write("\t\t\tfrm.submit();\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"./register_ok.jsp\" method=\"POST\" id=\"frm\">\t\n");
      out.write("\t\t<table border=\"1\" width=\"90%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"30%\">\n");
      out.write("\t\t\t\t\t시험학기\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td width=\"70%\">\n");
      out.write("\t\t\t\t\t<select id=\"year\" name=\"year\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t년\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<select id=\"semester\" name=\"semester\">\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t학기\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t<select id=\"gubun\" name=\"gubun\">\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">중간고사</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">기말고사</option>\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"30%\">\n");
      out.write("\t\t\t\t\t학과 및 학생이름\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td width=\"70%\">\n");
      out.write("\t\t\t\t\t<select id=\"college\" name=\"college\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<select id=\"dept\" name=\"dept\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t<select id=\"student\" name=\"student\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"30%\">\n");
      out.write("\t\t\t\t\t시험과목\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td width=\"70%\">\n");
      out.write("\t\t\t\t\t<select id=\"subject\" name=\"subject\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"30%\">\n");
      out.write("\t\t\t\t\t시험점수\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td width=\"70%\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"score\" name=\"score\" />\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"30%\">\n");
      out.write("\t\t\t\t\t시험날짜\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td width=\"70%\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"examdate\" name=\"examdate\" />\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"100%\" colspan=\"2\" align=\"center\">\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"btnSave\" name=\"btnSave\" value=\"저장\" />\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
